### ISSUE TITLE
Menu Links Don't Contain the Last /

### ISSUE THREAD

**Issue by graywolf336** [RocketChat/Rocket.Chat.Docs.Generator#7]
This is causing the images to not display on pages such as the welcome and user guide

**Comment by frdmn** [comment]
Two possibilities to solve this:

1. Adding a `<base href` on each page that makes sure to have an trailing slash in the base:

    ```
    <base href="http://<url>/docs/developer-guides/ui-and-theming/colors/">
    ```

2. Actually render the links in the left menu including a trailing slash, so users always end up with an URL that has a `/` at the end.

I'm not quite sure which one is the more suitable or clean way. What do you guys think?

**Comment by graywolf336** [comment]
@frdmn Number two is out of the picture, as it won't work and the only reason I know this is because I've tried it. The reason it doesn't work is because of the way Senna.js handles the push state.

I am close to being done with number one, as that was the conclusion I came to and am working on resolving it.
